### ISSUE TITLE
Rgarding simulated_spiral_data_example.py

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#11]
Hey Michael,
I am trying to run the create_simulated_data.py script in py27 and while doing so,  i get the following error
```
(py27) [tshisode@darwin simulated_spiral_data_example]$ python create_simulated_data.py
create_simulated_data.py:45: RuntimeWarning: divide by zero encountered in power
  MU=b*pow(D,a)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-tshisode'
Traceback (most recent call last):
  File "create_simulated_data.py", line 58, in <module>
    pt.plot_pts(resampled_ground_truth_curve,t,ax=ax1,fig=fig1)   
  File "build/bdist.linux-x86_64/egg/simba3d/plotting_tools.py", line 105, in plot_pts
  File "/home/tshisode/miniconda3/envs/py27/lib/python2.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2362, in scatter
    xs, ys, s=s, c=c, *args, **kwargs)
  File "/home/tshisode/miniconda3/envs/py27/lib/python2.7/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/home/tshisode/miniconda3/envs/py27/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4279, in scatter
    .format(c.shape, x.size, y.size))
ValueError: c of shape (150,) not acceptable as a color sequence for x with size 1280, y with size 1280

```
Any idea why?

**Comment by michael-m-rosenthal** [comment]
I will take a look and see if I can reproduce the error.

**Comment by michael-m-rosenthal** [comment]
yes, there was an error. The t on line 58 should have been tn which is a re-sampled version of the curve parametrization. The error has been fixed.

Thanks for bringing that up.
