### ISSUE TITLE
Extract 3D structure coordinate

### ISSUE THREAD

**Issue by oluwatosin-oluwadare** [nerettilab/SIMBA3D#3]
Hi ,

 I have not been able to produce a .mat output or convert from .npz to .mat using the simba3d -r and simba3d-convertion functons respectively.

I keep getting this error message:
`
Traceback (most recent call last):
  File "/home/x/.local/bin/simba3d-convertion", line 11, in <module>
    load_entry_point('SIMBA3D==1.0.0', 'console_scripts', 'simba3d-convertion')()
  File "build/bdist.linux-x86_64/egg/simba3d/convertion_tool.py", line 42, in main
  File "build/bdist.linux-x86_64/egg/simba3d/mp_manager.py", line 110, in convert
  File "build/bdist.linux-x86_64/egg/simba3d/mp_manager.py", line 80, in save_data
  File "/home/x/.local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 211, in savemat
    MW.put_variables(mdict)
  File "/home/x/.local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 846, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "/home/x/.local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 587, in write_top
    self.write(arr)
  File "/home/x/.local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 605, in write
    narr = to_writeable(arr)
  File "/home/x/.local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 443, in to_writeable
    return np.array([tuple(values)], dtype)
TypeError: data type not understood
`
Can some one please tell me what is wrong..
Thanks

Tosin

**Comment by michael-m-rosenthal** [comment]
How are you calling the conversation tool in the command line?

**Comment by oluwatosin-oluwadare** [comment]
I call the conversion this way-    simba3d-convertion ${outname} --ext_out .mat

**Comment by michael-m-rosenthal** [comment]
That looks like it should work as long as the variable outname is a npz
output result from simba3d.

Have you tried using the command directly? i.e.
> simba3d-convertion path/to/your/output_file.npz --ext_out .mat

Are you able to convert outputs generated in the tutorials?

**Comment by oluwatosin-oluwadare** [comment]
No, I  found out that it actually does the conversion to .mat, but just doesn't finish it without an error. I think it's okay for now. I am able to extract the 3D cordinates from the .mat generated before the error. 
 That is what's important to me. Thanks for your response.

**Comment by michael-m-rosenthal** [comment]
Okay let me know if it becomes an issue and you want me to try and debug it.

I don't have much to go on from here. It could be an issue with the results output, or there could be some differences in the python dependencies that throw an error.

I am going to close this for now, and if you want to open it again we can try to call the python script directly to see if a more helpful error message is provided.
